set(NEED_UNIX_DRIVER 1)
set(WANT_VOLK 0)
set(WANT_VULKAN 1)
set(WANT_OPENGL 1)
set(WANT_VULKAN 1)
set(WANT_OPENGL 1)
set(WANT_GLAD 1)
set(WANT_FONTCONFIG 1)
set(WANT_COREAUDIO 1)
set(WANT_COREMIDI 1)
set(GODOT_PLATFORM "macos")

option(ENABLE_METAL "Enable the Metal renderer" OFF)

add_compile_definitions(UNIX_ENABLED)