set(NEED_UNIX_DRIVER 1)
option(ENABLE_METAL "Enable the Metal renderer" ON)
option(ENABLE_VULKAN "Enable the Vulkan renderer" ON)
option(ENABLE_OPENGL "Enable the OpenGL renderer" ON)
option(ENABLE_GLAD "Enable GLAD OpenGL loader" ON)
option(ENABLE_COREAUDIO "Enable the CoreAudio driver" ON)
option(ENABLE_COREMIDI "Enable the CoreMIDI driver" ON)
option(ENABLE_OPENXR "Enable OpenXR" ON)
set(GODOT_PLATFORM "macos")
add_compile_definitions(MACOS_ENABLED)

add_compile_definitions(UNIX_ENABLED)
