add_subdirectory(2d)
add_subdirectory(3d)
add_subdirectory(audio)

# [[[cog
#   import cog
#   from cmake_builders import list_files
#   cog.outl('target_sources(scene PRIVATE')
#   for file in list_files(cog, '.'):
#       cog.outl(f'        {file}')
#   cog.outl(')')
# ]]]
target_sources(scene PRIVATE
        animated_texture.cpp
        animated_texture.h
        animation.cpp
        animation.h
        animation_library.cpp
        animation_library.h
        atlas_texture.cpp
        atlas_texture.h
        bit_map.cpp
        bit_map.h
        blit_material.cpp
        blit_material.h
        bone_map.cpp
        bone_map.h
        camera_attributes.cpp
        camera_attributes.h
        camera_texture.cpp
        camera_texture.h
        canvas_item_material.cpp
        canvas_item_material.h
        color_palette.cpp
        color_palette.h
        compositor.cpp
        compositor.h
        compressed_texture.cpp
        compressed_texture.h
        compressed_texture_resource_format.cpp
        compressed_texture_resource_format.h
        curve.cpp
        curve.h
        curve_texture.cpp
        curve_texture.h
        dpi_texture.cpp
        dpi_texture.h
        drawable_texture_2d.cpp
        drawable_texture_2d.h
        environment.cpp
        environment.h
        external_texture.cpp
        external_texture.h
        font.cpp
        font.h
        gradient.cpp
        gradient.h
        gradient_texture.cpp
        gradient_texture.h
        image_texture.cpp
        image_texture.h
        immediate_mesh.cpp
        immediate_mesh.h
        label_settings.cpp
        label_settings.h
        material.cpp
        material.h
        mesh.cpp
        mesh.h
        mesh_data_tool.cpp
        mesh_data_tool.h
        mesh_texture.cpp
        mesh_texture.h
        multimesh.cpp
        multimesh.h
        navigation_mesh.cpp
        navigation_mesh.h
        packed_scene.cpp
        packed_scene.h
        particle_process_material.cpp
        particle_process_material.h
        physics_material.cpp
        physics_material.h
        placeholder_textures.cpp
        placeholder_textures.h
        portable_compressed_texture.cpp
        portable_compressed_texture.h
        resource_format_text.cpp
        resource_format_text.h
        shader.cpp
        shader.h
        shader_include.cpp
        shader_include.h
        shader_include_resource_format.cpp
        shader_include_resource_format.h
        shader_resource_format.cpp
        shader_resource_format.h
        skeleton_profile.cpp
        skeleton_profile.h
        sky.cpp
        sky.h
        sprite_frames.cpp
        sprite_frames.h
        streamed_texture.cpp
        streamed_texture.h
        style_box.cpp
        style_box.h
        style_box_flat.cpp
        style_box_flat.h
        style_box_line.cpp
        style_box_line.h
        style_box_texture.cpp
        style_box_texture.h
        surface_tool.cpp
        surface_tool.h
        syntax_highlighter.cpp
        syntax_highlighter.h
        text_file.cpp
        text_file.h
        text_line.cpp
        text_line.h
        text_paragraph.cpp
        text_paragraph.h
        texture.cpp
        texture.h
        texture_rd.cpp
        texture_rd.h
        theme.cpp
        theme.h
        video_stream.cpp
        video_stream.h
        world_2d.cpp
        world_2d.h
)
# [[[end]]]
