#!/usr/bin/env python

Import("env")
Import("env_modules")

env_slang = env_modules.Clone()

# Thirdparty source files

thirdparty_obj = []

# Godot source files

module_obj = []

env_slang.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj

Export("env_slang")

# Needed to force rebuilding the module files when the thirdparty library is updated.
env.Depends(module_obj, thirdparty_obj)
